# Generated by Django 4.2.16 on 2024-10-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='users'),
        ),
    ]
