# Generated by Django 4.2.16 on 2024-10-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cooking_time', models.FloatField(help_text='in minutes')),
                ('ingredients', models.CharField(help_text='Ingredients must be separated by commas.', max_length=500)),
            ],
        ),
    ]
